### ISSUE TITLE
Error in latest gem (1.2.2): in rmodbus/server.rb wrong variable used

### ISSUE THREAD

**Issue by vanjabucic** [flipback/rmodbus#32]
Current github version of the file is correct, but the 1.2.2 gem has this error that is fairly severe and is throwing invalid address exceptions when it should not.
Variable @coils should be @holding_registers

def **parse_write_register_func**(req)
      &nbsp;&nbsp;&nbsp;addr = req[1,2].unpack('n')[0]
      &nbsp;&nbsp;&nbsp;return { :err => 2 } unless addr <= **@coils.size**
      &nbsp;&nbsp;&nbsp;val = req[3,2].unpack('n')[0]
      &nbsp;&nbsp;&nbsp;return { :err => 0, :addr => addr, :val => val }
end

**Comment by flipback** [comment]
Thanks for the report! Sorry I've forgotten to realise the next version. Please, update your gems.
