### ISSUE TITLE
EOFError with RTUClient

### ISSUE THREAD

**Issue by mtuckerb** [flipback/rmodbus#34]
I'm using the RTUClient module to connect to a MODBus device that is attached via serial->usb device (Keyspan) to my Mac (OSX 10.10). I try to read the holding registers and get  a holding error like [this](https://gist.github.com/mtuckerb/1d0ff136c6453688eefd). I can access the registers through a general purpose MODBus gui. Is this a bug, or am I doing something wrong?

**Comment by flipback** [comment]
Thanks for the report! It seems I've found the solution of the problem. But it needs to be tested. Could you check my bugfix from the repository, please? Before I'll publish gem. I can't do it on my own, because I haven't got any RTU devices at hand.

**Comment by mtuckerb** [comment]
That seems to work like a charm! Thank you.


Tucker Bradford
http://forgeover.com

On March 12, 2015 at 3:24:15 PM, Aleksey Timin (notifications@github.com) wrote:

Thanks for the report! It seems I've found the solution of the problem. But it needs to be tested. Could you check my bugfix from the repository, please? Before I'll publish gem. I can't do it on my own, because I haven't got any RTU devices at hand.

**Comment by flipback** [comment]
Excellent! I've released bugfix gem. So you can update yours. 
Thanks a lot for your help!
