### ISSUE TITLE
(0x11) Report Slave ID

### ISSUE THREAD

**Issue by gerardp** [flipback/rmodbus#49]
Hi,
I have a doubt, it's implemented the function (0x11) Report Slave ID? i can't find it in the documentation.

Thanks

**Comment by flipback** [comment]
Sorry, but the library doesn't support the function.

**Comment by gerardp** [comment]
Any chances to add this functionality?

**Comment by flipback** [comment]
I wish I had time to do it. Actually I haven't been maintaining the project for a long time.. In my circumstance it's hardly possible. 

But you can try implementing it on your own by using `query` method:

https://github.com/flipback/rmodbus/blob/master/lib/rmodbus/slave.rb#L242
